# Generated by Django 3.0.6 on 2020-05-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='page',
            name='subtitle',
            field=models.CharField(default=True, max_length=500, verbose_name='Nombre Alumno y Grado'),
        ),
    ]
