# Generated by Django 3.0.5 on 2020-05-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
