# Generated by Django 3.0.6 on 2020-05-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smr', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Imagen')),
                ('dam', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Imagens')),
            ],
            options={
                'verbose_name': 'imágen',
                'verbose_name_plural': 'imágenes',
            },
        ),
    ]
