# Generated by Django 3.0.6 on 2020-05-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='dam',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='DAM'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='smr',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='SMR'),
        ),
    ]
