# Generated by Django 3.0.6 on 2020-05-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200525_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('smr', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='SMR')),
                ('dam', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='DAM')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'entrada',
                'verbose_name_plural': 'entradas',
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
