# Generated by Django 3.0.6 on 2020-05-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200525_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes',
            name='slider1',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='slider1'),
        ),
        migrations.AddField(
            model_name='imagenes',
            name='slider2',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='slider2'),
        ),
        migrations.AddField(
            model_name='imagenes',
            name='slider3',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='slider3'),
        ),
        migrations.AddField(
            model_name='imagenes',
            name='slider4',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='slider4'),
        ),
    ]
